model_handler: 
    name: dtfmel_gen
    params:
        default: null
do_train: true

lr_params:
  lr: 0.0001
  sched_gamma: 0.5
  sched_step: 100

batch_size: 32

losses:
    l2: 1.
    l1_reg: 0.02

epochs: 500
validate_each_epoch: 1
