model_handler: 
    name: dtfmel_gen
    params:
        default: null
do_train: true

lr_params:
  lr: 0.001
  sched_gamma: 0.96
  sched_step: 1

batch_size: 32

losses:
    l2: 1.

epochs: 500
validate_each_epoch: 1
