model_handler: 
    name: dtf_gen
    params:
        default: null
do_train: true

lr_params:
  lr: 0.00001
  sched_gamma: 0.5
  sched_step: 20 

batch_size: 32

losses:
    ce: 1.

epochs: 500
validate_each_epoch: 1
